create database employeemanagement;
use employeemanagement;
drop database employeemanagement;
show tables;
desc employee;
desc department;
desc location;
desc department_location;
desc project;
desc project_employees;
select * from employee;
select * from department;
select * from department_location;
select * from location;
select * from project;
select * from  project_employees;
drop table employee;
drop table department;
drop table location;
drop table department_location;
select count(*) from employee e where department_id = 1;